import {
  ALPHANUMERIC,
  DJANGO_CHARS,
  PRINTABLE_ASCII,
  URLSAFE,
  WORDPRESS_SECRET_CHARS,
  URL_UNRESERVED,
  base64,
  base64url,
  fernetBase64url,
  hex,
  randomString,
  randomIndex,
  secureBytes,
  uuidV4,
} from './random.js';
import { long as EFF_LONG_WORDS } from '@wordlist/english-eff/long';
import {
  encodeBase32,
  encodeBase32Crockford,
  encodeBase32Hex,
  encodeBase58,
} from './adapters/encoding.js';
import { generateNanoId, generateUuidV7 } from './adapters/identifiers.js';
import { generateOtpSecret } from './adapters/otp.js';
import { generatePasetoV4LocalKey } from './adapters/paseto.js';

const bytesOption = (defaultValue = 32, min = 1, max = 4096) => ({
  name: 'bytes',
  cliName: 'bytes',
  type: 'integer',
  unit: 'bytes',
  default: defaultValue,
  min,
  max,
});

const lengthOption = (defaultValue, min = 1, max = 16384) => ({
  name: 'length',
  cliName: 'length',
  type: 'integer',
  unit: 'characters',
  default: defaultValue,
  min,
  max,
});

const integerOption = (name, defaultValue, min, max, unit = name) => ({
  name,
  cliName: name.replaceAll(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`),
  type: 'integer',
  default: defaultValue,
  min,
  max,
  unit,
});

const enumOption = (name, defaultValue, choices) => ({
  name,
  cliName: name.replaceAll(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`),
  type: 'enum',
  default: defaultValue,
  choices,
});

const booleanOption = (name, defaultValue) => ({
  name,
  cliName: name.replaceAll(/[A-Z]/gu, (letter) => `-${letter.toLowerCase()}`),
  type: 'boolean',
  default: defaultValue,
});

function bytes(options, fallback) {
  return options.bytes ?? fallback;
}

function length(options, fallback) {
  return options.length ?? fallback;
}

function phoenixSecret(size) {
  // Mirrors Phoenix 1.8 phx.gen.secret: strong_rand_bytes(length),
  // Base64 without padding, then truncate to exactly `length` chars.
  return secureBytes(size).toString('base64').replace(/=+$/u, '').slice(0, size);
}

function wordpressSalts() {
  const keys = [
    'AUTH_KEY',
    'SECURE_AUTH_KEY',
    'LOGGED_IN_KEY',
    'NONCE_KEY',
    'AUTH_SALT',
    'SECURE_AUTH_SALT',
    'LOGGED_IN_SALT',
    'NONCE_SALT',
  ];

  return keys
    .map((key) => {
      // WordPress core uses wp_generate_password(64, true, true) for salts.
      // Its alphabet intentionally excludes single quotes and backslashes, so
      // these lines can be pasted directly inside PHP single-quoted strings.
      const value = randomString(64, WORDPRESS_SECRET_CHARS);
      return `define('${key}', '${value}');`;
    })
    .join('\n');
}

function dicewarePassphrase(wordCount, separator) {
  const separators = { hyphen: '-', space: ' ', underscore: '_', dot: '.' };
  const words = [];
  for (let i = 0; i < wordCount; i += 1) {
    words.push(EFF_LONG_WORDS[randomIndex(EFF_LONG_WORDS.length)]);
  }
  return words.join(separators[separator]);
}

export const PRESETS = [
  {
    id: 'generic:hex',
    aliases: ['hex'],
    category: 'Generic',
    label: 'Hex token',
    description: 'Cryptographically secure random bytes encoded as lowercase hex.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => hex(bytes(o, 32)),
  },
  {
    id: 'generic:base64',
    aliases: ['base64'],
    category: 'Generic',
    label: 'Base64 token',
    description: 'Cryptographically secure random bytes encoded as padded Base64.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => base64(bytes(o, 32)),
  },
  {
    id: 'generic:base64url',
    aliases: ['base64url', 'urlsafe'],
    category: 'Generic',
    label: 'Base64URL token',
    description: 'Cryptographically secure random bytes encoded as unpadded Base64URL.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => base64url(bytes(o, 32)),
  },
  {
    id: 'generic:alphanumeric',
    aliases: ['alphanumeric', 'alnum'],
    category: 'Generic',
    label: 'Alphanumeric secret',
    description: 'Random A-Z, a-z and 0-9 characters using unbiased secure sampling.',
    env: 'SECRET_KEY',
    option: lengthOption(48),
    generate: (o) => randomString(length(o, 48), ALPHANUMERIC),
  },
  {
    id: 'generic:password',
    aliases: ['password', 'passwd'],
    category: 'Generic',
    label: 'Strong machine password',
    description: 'Random printable ASCII password for machine-managed credentials.',
    env: 'PASSWORD',
    option: lengthOption(32),
    generate: (o) => randomString(length(o, 32), PRINTABLE_ASCII),
  },
  {
    id: 'generic:base32',
    aliases: ['base32', 'rfc4648-base32'],
    category: 'Generic',
    label: 'Base32 token',
    description: 'RFC 4648 uppercase Base32 secret, optionally padded.',
    env: 'SECRET_KEY',
    options: [bytesOption(32), booleanOption('padding', false)],
    generate: (o) => encodeBase32(secureBytes(o.bytes), o.padding),
  },
  {
    id: 'generic:urlsafe-string',
    aliases: ['url-string', 'url-secret'],
    category: 'Generic',
    label: 'Exact-length URL-safe secret',
    description: 'Exact-length random string using the RFC 3986 unreserved alphabet.',
    env: 'SECRET_KEY',
    option: lengthOption(48),
    generate: (o) => randomString(o.length, URL_UNRESERVED),
  },
  {
    id: 'generic:passphrase',
    aliases: ['passphrase', 'diceware'],
    category: 'Generic',
    label: 'EFF Diceware passphrase',
    description: 'Memorable passphrase generated from the 7,776-word EFF long wordlist.',
    env: 'PASSPHRASE',
    options: [
      integerOption('words', 6, 4, 20, 'words'),
      enumOption('separator', 'hyphen', ['hyphen', 'space', 'underscore', 'dot']),
    ],
    generate: (o) => dicewarePassphrase(o.words, o.separator),
  },
  {
    id: 'uuid:v4',
    aliases: ['uuid', 'uuid4'],
    category: 'Identifiers',
    label: 'UUID version 4',
    description: 'CSPRNG-backed RFC 9562 UUIDv4 identifier with 122 random bits.',
    env: null,
    sensitivity: 'public',
    option: null,
    generate: () => uuidV4(),
  },
  {
    id: 'uuid:v7',
    aliases: ['uuid7'],
    category: 'Identifiers',
    label: 'UUID version 7',
    description: 'Time-ordered RFC 9562 UUIDv7 identifier that exposes its generation millisecond.',
    env: null,
    sensitivity: 'public',
    option: null,
    generate: () => generateUuidV7(),
  },

  {
    id: 'python:token-hex',
    aliases: ['token-hex', 'python-hex'],
    category: 'Python',
    label: 'Python secrets.token_hex',
    description: 'Format-compatible with Python secrets.token_hex(nbytes).',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => hex(bytes(o, 32)),
  },
  {
    id: 'python:token-urlsafe',
    aliases: ['token-urlsafe', 'python-urlsafe'],
    category: 'Python',
    label: 'Python secrets.token_urlsafe',
    description: 'Format-compatible URL-safe Base64 token generated from n random bytes.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => base64url(bytes(o, 32)),
  },
  {
    id: 'django:secret-key',
    aliases: ['django'],
    category: 'Python',
    label: 'Django SECRET_KEY',
    description: 'Django-compatible 50-character SECRET_KEY using Django’s current alphabet.',
    env: 'DJANGO_SECRET_KEY',
    option: null,
    generate: () => randomString(50, DJANGO_CHARS),
  },
  {
    id: 'flask:secret-key',
    aliases: ['flask'],
    category: 'Python',
    label: 'Flask SECRET_KEY',
    description: 'Matches Flask documentation’s recommended secrets.token_hex() style.',
    env: 'FLASK_SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => hex(bytes(o, 32)),
  },
  {
    id: 'fastapi:jwt-secret',
    aliases: ['fastapi'],
    category: 'Python',
    label: 'FastAPI JWT SECRET_KEY',
    description: 'Matches FastAPI tutorial’s `openssl rand -hex 32` HS256 secret style.',
    env: 'SECRET_KEY',
    option: null,
    generate: () => hex(32),
  },
  {
    id: 'cryptography:fernet',
    aliases: ['fernet'],
    category: 'Python',
    label: 'cryptography Fernet key',
    description: 'Fernet-compatible URL-safe Base64-encoded 32-byte key with padding.',
    env: 'FERNET_KEY',
    option: null,
    generate: () => fernetBase64url(32),
  },

  {
    id: 'express:session-secret',
    aliases: ['express-session'],
    category: 'JavaScript',
    label: 'Express session secret',
    description: '32 bytes of entropy for express-session HMAC signing, Base64URL encoded.',
    env: 'SESSION_SECRET',
    option: bytesOption(32, 32),
    generate: (o) => base64url(bytes(o, 32)),
  },
  {
    id: 'express:cookie-secret',
    aliases: ['express-cookie', 'cookie-parser'],
    category: 'JavaScript',
    label: 'Express cookie secret',
    description: 'High-entropy signing secret suitable for cookie-parser signed cookies.',
    env: 'COOKIE_SECRET',
    option: bytesOption(32, 32),
    generate: (o) => base64url(bytes(o, 32)),
  },
  {
    id: 'authjs:secret',
    aliases: ['authjs', 'nextauth'],
    category: 'JavaScript',
    label: 'Auth.js AUTH_SECRET',
    description: 'High-entropy random token suitable for Auth.js AUTH_SECRET.',
    env: 'AUTH_SECRET',
    option: null,
    generate: () => base64url(32),
  },
  {
    id: 'iron-session:password',
    aliases: ['iron-session', 'iron'],
    category: 'JavaScript',
    label: 'iron-session password',
    description: '64-character high-entropy password; iron-session requires at least 32 characters.',
    env: 'SESSION_PASSWORD',
    option: lengthOption(64, 32),
    generate: (o) => randomString(length(o, 64), ALPHANUMERIC),
  },
  {
    id: 'better-auth:secret',
    aliases: ['better-auth', 'betterauth'],
    category: 'JavaScript',
    label: 'Better Auth secret',
    description: 'High-entropy Base64 secret for BETTER_AUTH_SECRET or AUTH_SECRET.',
    env: 'BETTER_AUTH_SECRET',
    option: bytesOption(32, 24),
    generate: (o) => base64(o.bytes),
  },
  {
    id: 'nuxt:session-password',
    aliases: ['nuxt-session', 'nuxt-auth-utils'],
    category: 'JavaScript',
    label: 'Nuxt session password',
    description: 'High-entropy Base64URL value for NUXT_SESSION_PASSWORD.',
    env: 'NUXT_SESSION_PASSWORD',
    option: bytesOption(32, 24),
    generate: (o) => base64url(o.bytes),
  },
  {
    id: 'adonis:app-key',
    aliases: ['adonis', 'adonis-app-key'],
    category: 'JavaScript',
    label: 'AdonisJS APP_KEY',
    description: 'Cryptographically secure 32-character application key for AdonisJS.',
    env: 'APP_KEY',
    option: null,
    generate: () => randomString(32, ALPHANUMERIC),
  },

  {
    id: 'rails:secret-key-base',
    aliases: ['rails', 'rails-secret'],
    category: 'Ruby / PHP / Elixir',
    label: 'Rails secret_key_base',
    description: '128 hex characters, matching Rails SecureRandom.hex(64) / bin/rails secret style.',
    env: 'SECRET_KEY_BASE',
    option: null,
    generate: () => hex(64),
  },
  {
    id: 'laravel:app-key',
    aliases: ['laravel'],
    category: 'Ruby / PHP / Elixir',
    label: 'Laravel APP_KEY',
    description: 'Laravel AES-256 application key: `base64:` plus 32 random bytes.',
    env: 'APP_KEY',
    option: null,
    generate: () => `base64:${base64(32)}`,
  },
  {
    id: 'symfony:app-secret',
    aliases: ['symfony'],
    category: 'Ruby / PHP / Elixir',
    label: 'Symfony APP_SECRET',
    description: 'Long immutable random string suitable for Symfony kernel.secret / APP_SECRET.',
    env: 'APP_SECRET',
    option: null,
    generate: () => hex(32),
  },
  {
    id: 'phoenix:secret-key-base',
    aliases: ['phoenix', 'phx'],
    category: 'Ruby / PHP / Elixir',
    label: 'Phoenix SECRET_KEY_BASE',
    description: 'Mirrors `mix phx.gen.secret` default: exactly 64 Base64 characters without padding.',
    env: 'SECRET_KEY_BASE',
    option: lengthOption(64, 32, 4096),
    generate: (o) => phoenixSecret(length(o, 64)),
  },
  {
    id: 'wordpress:salts',
    aliases: ['wordpress', 'wp-salts'],
    category: 'Ruby / PHP / Elixir',
    label: 'WordPress keys & salts',
    description: 'Generates all 8 wp-config.php authentication keys and salts as copy-ready PHP lines.',
    env: null,
    option: null,
    multiline: true,
    generate: () => wordpressSalts(),
  },
  {
    id: 'codeigniter:encryption-key',
    aliases: ['codeigniter', 'ci-encryption-key'],
    category: 'Ruby / PHP / Elixir',
    label: 'CodeIgniter encryption key',
    description: 'Copy-safe 32-byte CodeIgniter encryption key with a decoding prefix.',
    env: 'encryption.key',
    options: [enumOption('encoding', 'hex2bin', ['hex2bin', 'base64'])],
    generate: (o) => o.encoding === 'hex2bin' ? `hex2bin:${hex(32)}` : `base64:${base64(32)}`,
  },
  {
    id: 'rails:master-key',
    aliases: ['rails-master', 'rails-credentials-key'],
    category: 'Ruby / PHP / Elixir',
    label: 'Rails credentials master key',
    description: 'Current Rails ActiveSupport::EncryptedFile key: 16 random bytes as 32 lowercase hex characters.',
    env: 'RAILS_MASTER_KEY',
    option: null,
    generate: () => hex(16),
  },
  {
    id: 'spring:base64-key',
    aliases: ['spring-base64', 'spring-security-key'],
    category: 'Java / .NET',
    label: 'Spring Security Base64 key',
    description: 'Spring Base64StringKeyGenerator-compatible key with a secure 32-byte minimum.',
    env: null,
    option: bytesOption(32, 32, 128),
    generate: (o) => base64(o.bytes),
  },
  {
    id: 'github:webhook-secret',
    aliases: ['github-webhook', 'webhook-secret'],
    category: 'Webhooks / OAuth',
    label: 'GitHub webhook secret',
    description: 'Application-chosen high-entropy secret for validating GitHub webhook deliveries.',
    env: 'GITHUB_WEBHOOK_SECRET',
    options: [bytesOption(32, 32, 128), enumOption('encoding', 'base64url', ['base64url', 'hex'])],
    generate: (o) => o.encoding === 'hex' ? hex(o.bytes) : base64url(o.bytes),
  },
  {
    id: 'oauth:pkce-verifier',
    aliases: ['pkce', 'code-verifier'],
    category: 'Webhooks / OAuth',
    label: 'OAuth PKCE code verifier',
    description: 'Request-bound RFC 7636 verifier using the RFC 3986 unreserved alphabet.',
    env: null,
    option: lengthOption(43, 43, 128),
    generate: (o) => randomString(o.length, URL_UNRESERVED),
  },

  {
    id: 'jwt:hs256',
    aliases: ['hs256'],
    category: 'JWT / Crypto',
    label: 'JWT HS256 key',
    description: '256-bit HMAC key, satisfying RFC 7518 minimum size for HS256.',
    env: 'JWT_SECRET',
    option: null,
    generate: () => base64url(32),
  },
  {
    id: 'jwt:hs384',
    aliases: ['hs384'],
    category: 'JWT / Crypto',
    label: 'JWT HS384 key',
    description: '384-bit HMAC key, satisfying RFC 7518 minimum size for HS384.',
    env: 'JWT_SECRET',
    option: null,
    generate: () => base64url(48),
  },
  {
    id: 'jwt:hs512',
    aliases: ['hs512'],
    category: 'JWT / Crypto',
    label: 'JWT HS512 key',
    description: '512-bit HMAC key, satisfying RFC 7518 minimum size for HS512.',
    env: 'JWT_SECRET',
    option: null,
    generate: () => base64url(64),
  },
  {
    id: 'aes:128',
    aliases: ['aes128'],
    category: 'JWT / Crypto',
    label: 'AES-128 key',
    description: '128-bit uniformly random AES key encoded as hex.',
    env: 'AES_KEY',
    option: null,
    generate: () => hex(16),
  },
  {
    id: 'aes:192',
    aliases: ['aes192'],
    category: 'JWT / Crypto',
    label: 'AES-192 key',
    description: '192-bit uniformly random AES key encoded as hex.',
    env: 'AES_KEY',
    option: null,
    generate: () => hex(24),
  },
  {
    id: 'aes:256',
    aliases: ['aes256'],
    category: 'JWT / Crypto',
    label: 'AES-256 key',
    description: '256-bit uniformly random AES key encoded as hex.',
    env: 'AES_KEY',
    option: null,
    generate: () => hex(32),
  },
  {
    id: 'chacha20-poly1305:key',
    aliases: ['chacha20', 'chacha'],
    category: 'JWT / Crypto',
    label: 'ChaCha20-Poly1305 key',
    description: '256-bit uniformly random key for ChaCha20-Poly1305, encoded as hex.',
    env: 'CHACHA20_KEY',
    option: null,
    generate: () => hex(32),
  },
  {
    id: 'hmac:sha256',
    aliases: ['hmac256'],
    category: 'JWT / Crypto',
    label: 'HMAC-SHA256 key',
    description: '256-bit random HMAC key encoded as Base64URL.',
    env: 'HMAC_SECRET',
    option: null,
    generate: () => base64url(32),
  },
  {
    id: 'hmac:sha512',
    aliases: ['hmac512'],
    category: 'JWT / Crypto',
    label: 'HMAC-SHA512 key',
    description: '512-bit random HMAC key encoded as Base64URL.',
    env: 'HMAC_SECRET',
    option: null,
    generate: () => base64url(64),
  },
  {
    id: 'hmac:sha384',
    aliases: ['hmac384'],
    category: 'JWT / Crypto',
    label: 'HMAC-SHA384 key',
    description: '384-bit random HMAC key encoded as Base64URL.',
    env: 'HMAC_SECRET',
    option: null,
    generate: () => base64url(48),
  },
  {
    id: 'totp:secret',
    aliases: ['totp', 'otp'],
    category: 'JWT / Crypto',
    label: 'TOTP shared secret',
    description: '160-bit random TOTP/HOTP shared secret encoded as RFC 4648 Base32 without padding.',
    env: 'TOTP_SECRET',
    option: bytesOption(20, 16, 128),
    generate: (o) => generateOtpSecret(bytes(o, 20)),
  },
  {
    id: 'hotp:secret',
    aliases: ['hotp'],
    category: 'JWT / Crypto',
    label: 'HOTP shared secret',
    description: 'RFC 4226 shared secret encoded as uppercase unpadded Base32.',
    env: 'HOTP_SECRET',
    option: bytesOption(20, 16, 128),
    generate: (o) => generateOtpSecret(o.bytes),
  },
  {
    id: 'wireguard:preshared-key',
    aliases: ['wireguard-psk', 'wg-psk'],
    category: 'Infrastructure',
    label: 'WireGuard preshared key',
    description: 'wg-compatible 32-byte preshared key encoded as padded Base64.',
    env: null,
    option: null,
    generate: () => base64(32),
  },
  {
    id: 'paseto:v4-local-key',
    aliases: ['paseto-local', 'k4-local'],
    category: 'JWT / Crypto',
    label: 'PASETO v4.local PASERK',
    description: '32-byte PASETO v4.local key serialized as a k4.local PASERK.',
    env: 'PASETO_LOCAL_KEY',
    option: null,
    generate: () => generatePasetoV4LocalKey(),
  },
  {
    id: 'sodium:secretbox-key',
    aliases: ['secretbox', 'sodium-secretbox'],
    category: 'JWT / Crypto',
    label: 'libsodium secretbox key',
    description: '32-byte crypto_secretbox key encoded for copy-safe storage.',
    env: 'SECRETBOX_KEY',
    options: [enumOption('encoding', 'base64', ['base64', 'hex'])],
    generate: (o) => o.encoding === 'hex' ? hex(32) : base64(32),
  },
  {
    id: 'consul:gossip-key',
    aliases: [],
    category: 'Infrastructure',
    label: 'Consul gossip encryption key',
    description: 'Consul-compatible 32-byte gossip key encoded as padded Base64.',
    env: null,
    option: null,
    generate: () => base64(32),
  },
  {
    id: 'nomad:gossip-key',
    aliases: [],
    category: 'Infrastructure',
    label: 'Nomad gossip encryption key',
    description: 'Nomad-compatible AES-128 or AES-256 gossip key encoded as padded Base64.',
    env: null,
    option: integerOption('bits', 256, 128, 256, 'bits'),
    validateOptions: (o) => {
      if (![128, 256].includes(o.bits)) throw new Error('--bits must be one of: 128, 256.');
    },
    generate: (o) => base64(o.bits / 8),
  },
  {
    id: 'rabbitmq:erlang-cookie',
    aliases: [],
    category: 'Infrastructure',
    label: 'RabbitMQ Erlang cookie',
    description: 'Alphanumeric cluster cookie for RabbitMQ nodes, with secure .erlang.cookie bundle output.',
    env: 'RABBITMQ_ERLANG_COOKIE',
    bundleFilename: '.erlang.cookie',
    bundleRole: 'cookie',
    option: lengthOption(64, 32, 255),
    generate: (o) => randomString(o.length, ALPHANUMERIC),
  },
  {
    id: 'directus:secret',
    aliases: [],
    category: 'JavaScript',
    label: 'Directus project secret',
    description: 'Persistent 32-byte Base64URL secret for Directus production deployments.',
    env: 'SECRET',
    option: null,
    generate: () => base64url(32),
  },
  {
    id: 'payload:secret',
    aliases: [],
    category: 'JavaScript',
    label: 'Payload CMS secret',
    description: '32-byte Base64URL secret for Payload encryption workflows.',
    env: 'PAYLOAD_SECRET',
    option: null,
    generate: () => base64url(32),
  },
  {
    id: 'keystone:session-secret',
    aliases: [],
    category: 'JavaScript',
    label: 'Keystone session secret',
    description: 'URL-safe Keystone session secret; Keystone requires at least 32 characters.',
    env: 'SESSION_SECRET',
    option: lengthOption(64, 32, 256),
    generate: (o) => randomString(o.length, URLSAFE),
  },
  {
    id: 'generic:base58',
    aliases: [],
    category: 'Generic',
    label: 'Base58 token',
    description: 'Cryptographically secure random bytes encoded as canonical Base58.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => encodeBase58(secureBytes(o.bytes)),
  },
  {
    id: 'generic:base32hex',
    aliases: [],
    category: 'Generic',
    label: 'Base32Hex token',
    description: 'RFC 4648 Base32Hex secret, optionally padded.',
    env: 'SECRET_KEY',
    options: [bytesOption(32), booleanOption('padding', false)],
    generate: (o) => encodeBase32Hex(secureBytes(o.bytes), o.padding),
  },
  {
    id: 'generic:base32-crockford',
    aliases: [],
    category: 'Generic',
    label: 'Crockford Base32 token',
    description: 'Human-friendly Crockford Base32 encoding of cryptographically secure random bytes.',
    env: 'SECRET_KEY',
    option: bytesOption(32),
    generate: (o) => encodeBase32Crockford(secureBytes(o.bytes)),
  },
  {
    id: 'id:nanoid',
    aliases: [],
    category: 'Identifiers',
    label: 'NanoID identifier',
    description: 'URL-friendly NanoID identifier; this is public identifier material, not a secret.',
    env: null,
    sensitivity: 'public',
    option: lengthOption(21, 1, 256),
    generate: (o) => generateNanoId(o.length),
  },
];
